notifications:
    email: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install --upgrade pip setuptools
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt
    - pip install -e .
script:
    - flake8
    - py.test -vv
